#!/bin/sh 

curl http://127.0.0.1:8080/version

# Expect output similar to 
#
#
# {
#  "major": "1",
#  "minor": "4",
#  "gitVersion": "v1.5.2+coreos.0",
#  "gitCommit": "ec2b52fabadf824a42b66b6729fe4cff2c62af8c",
#  "gitTreeState": "clean",
#  "buildDate": "2016-11-14T19:42:00Z",
#  "goVersion": "go1.6.3",
#  "compiler": "gc",
#  "platform": "linux/amd64"
# }
#
# 